name: Example workflow for node using Snyk

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --json-file-output=snyk.json

      - name: Upload Snyk node scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: snyk.json
